version: "{branch} {build}"

cache:
  - C:\Users\appveyor\.m2 -> pom.xml

install:
  # set JAVA_HOME path to JDK 1.7
  - SET JAVA_HOME=C:\Program Files\Java\jdk1.8.0

  # set PATH
  - SET PATH=%JAVA_HOME%\bin;%PATH%

  # check Java version
  - java -version

  - SET MAVEN_OPTS="-Dmaven.repo.local=C:/Users/appveyor/.m2"
build_script:
  - mvn clean compile -DskipTests

test_script:
  - mvn test
